### ISSUE TITLE
bfc with MiSeq data?

### ISSUE THREAD

**Issue by peterdfields** [lh3/bfc#10]
Is it possible to use bfc with MiSeq data with read lengths on the order of 250 to 300bp?

**Comment by lh3** [comment]
It should be fine, but I haven't tried that by myself.

**Comment by peterdfields** [comment]
Okay, great! So far when I try to run the reads through I'm getting a very generic error message of:

**\* Error in `bfc': malloc(): memory corruption: 0x00007f7b3c000089 ***

The same error does not arise when using bfc for standard standard HiSeq reads with lengths between 100 and 150. I can send a sample set of reads if that would be useful.
