### ISSUE TITLE
BFC-ht versus BFC-bf

### ISSUE THREAD

**Issue by macmanes** [lh3/bfc#2]
The arXiv preprint reports that the ht mode of BFC is generally more accurate than the bf mode.. Does the code in the readme e.g., `bfc -s 3g -t16 reads.fq.gz | gzip -1 > corrected.fq.gz` specify the ht or bf mode?

**Comment by lh3** [comment]
The "master" branch is for BFC-ht (or BFC in brief). BFC-bf is on the [kmc branch](https://github.com/lh3/bfc/tree/kmc).
