### ISSUE TITLE
Memory consuming

### ISSUE THREAD

**Issue by simoncchu** [lh3/bfc#4]
Hi Heng,

I am using bfc to do error correction on a 32G server. The reads are from illumina with length 100bp, and coverage is ~10x. I am using  command "bfc -s 3g -t 5 -k 19 -b 20 XXX.fq". It seems the program is always killed because the memory consuming is high. Is there a way to run with less memory usage? Thank you.

Best,
Chong

**Comment by lh3** [comment]
See the preprint. BFC will require ~64-80GB RAM. There is BFC-bf on the kmc branch, you need to:

```
git clone https://github.com/lh3/bfc.git
cd bfc
git checkout -b kmc remotes/origin/kmc
make
mkdir tmp
path/to/kmc -k33 reads.fq.gz reads.kmc tmp
./bfc -t16 reads.kmc reads.fq.gz > ec.fq
```

The above runs in 16GB or so, but is slightly less accurate. Also, I haven't tried to apply BFC on 10X data. In addition, you can choose bloocoo, lighter and bless. They also use less RAM. Their binaries can be found at:

https://sourceforge.net/projects/biobin/files/error_correction/
